from pathlib import Path

p = Path('src/ui/face_search_panel.rs')
s = p.read_text(encoding='utf-8')

repls = [
("use crate::face_similarity::{FaceEmbeddingRevision, FaceSimilarityQuery};\n", "use crate::face_similarity::{FaceEmbeddingRevision, FaceSimilarityQuery};\nuse crate::people_effective;\n"),
("    suggestions: Vec<IndexedFaceSuggestion>,\n    selected_face_id: Option<String>,\n", "    suggestions: Vec<IndexedFaceSuggestion>,\n    suggestion_names: HashMap<String, String>,\n    filter_text: String,\n    selected_face_id: Option<String>,\n"),
("            suggestions: Vec::new(),\n            selected_face_id: None,\n", "            suggestions: Vec::new(),\n            suggestion_names: HashMap::new(),\n            filter_text: String::new(),\n            selected_face_id: None,\n"),
("                            self.face_search_ui.suggestions = suggestions;\n                            let selected_exists", "                            self.face_search_ui.suggestions = suggestions;\n                            self.refresh_face_suggestion_names();\n                            let selected_exists"),
("    pub(super) fn refresh_face_suggestions(&mut self) {\n", "    fn refresh_face_suggestion_names(&mut self) {\n        self.face_search_ui.suggestion_names.clear();\n        let Ok(conn) = crate::db::open(&self.db_path) else {\n            return;\n        };\n        let Ok(catalog) = people_effective::load(&conn) else {\n            return;\n        };\n        let names = catalog\n            .people\n            .iter()\n            .filter_map(|person| {\n                let name = person.display_name.as_deref()?.trim();\n                (!name.is_empty()).then(|| (person.person_id.as_str(), name.to_owned()))\n            })\n            .collect::<HashMap<_, _>>();\n        for member in &catalog.members {\n            if member.ignored || member.detached {\n                continue;\n            }\n            let Some(person_id) = member.person_id.as_deref() else {\n                continue;\n            };\n            let Some(name) = names.get(person_id) else {\n                continue;\n            };\n            self.face_search_ui\n                .suggestion_names\n                .insert(member.face_id.clone(), name.clone());\n        }\n    }\n\n    pub(super) fn refresh_face_suggestions(&mut self) {\n"),
("                ui.separator();\n                ui.strong(\"People / searchable faces in database\");\n", "                ui.separator();\n                ui.strong(\"People / searchable faces in database\");\n                ui.add(\n                    egui::TextEdit::singleline(&mut self.face_search_ui.filter_text)\n                        .hint_text(\"Filter named people…\")\n                        .desired_width(ui.available_width().min(360.0)),\n                );\n"),
("                let suggestions = self.face_search_ui.suggestions.clone();\n", "                let filter = self.face_search_ui.filter_text.trim().to_lowercase();\n                let suggestions = self\n                    .face_search_ui\n                    .suggestions\n                    .iter()\n                    .filter(|face| {\n                        filter.is_empty()\n                            || self\n                                .face_search_ui\n                                .suggestion_names\n                                .get(&face.face_id)\n                                .is_some_and(|name| name.to_lowercase().contains(&filter))\n                    })\n                    .cloned()\n                    .collect::<Vec<_>>();\n                if !filter.is_empty() {\n                    ui.small(format!(\"{} matching named People\", suggestions.len()));\n                }\n"),
("                                            if let Some(group_size) = face.group_size {\n                                                ui.small(format!(\n                                                    \"Person · {group_size} face{}\",\n                                                    if group_size == 1 { \"\" } else { \"s\" }\n                                                ));\n", "                                            if let Some(name) = self\n                                                .face_search_ui\n                                                .suggestion_names\n                                                .get(&face.face_id)\n                                            {\n                                                ui.strong(truncate(name, 16));\n                                            }\n                                            if let Some(group_size) = face.group_size {\n                                                ui.small(format!(\n                                                    \"Person · {group_size} face{}\",\n                                                    if group_size == 1 { \"\" } else { \"s\" }\n                                                ));\n")
]

for old, new in repls:
    if old not in s:
        raise SystemExit(f'missing anchor: {old[:120]!r}')
    s = s.replace(old, new, 1)

p.write_text(s, encoding='utf-8')
