from pathlib import Path

path = Path("src/db.rs")
text = path.read_text(encoding="utf-8")
old = '''pub fn ann_index_signature(db_path: &Path) -> Result<u64> {\n    let conn = open(db_path)?;\n    let mut stmt = conn.prepare(\n        "SELECT rowid, path, size, modified, COALESCE(embedding_dim, 0), embedding_normalized FROM images WHERE embedding IS NOT NULL ORDER BY rowid",\n    )?;\n    let rows = stmt.query_map([], |row| {\n        Ok((\n            row.get::<_, i64>(0)?,\n            row.get::<_, String>(1)?,\n            row.get::<_, i64>(2)?,\n            row.get::<_, i64>(3)?,\n            row.get::<_, i64>(4)?,\n            row.get::<_, bool>(5)?,\n        ))\n    })?;\n    let mut hasher = std::collections::hash_map::DefaultHasher::new();\n    1_u32.hash(&mut hasher); // bump when embedding/index semantics change.\n    for row in rows {\n        let (rowid, path, size, modified, dim, normalized) = row?;\n        rowid.hash(&mut hasher);\n        path.hash(&mut hasher);\n        size.hash(&mut hasher);\n        modified.hash(&mut hasher);\n        dim.hash(&mut hasher);\n        normalized.hash(&mut hasher);\n    }\n    Ok(hasher.finish())\n}\n'''
new = '''pub fn ann_index_signature(db_path: &Path) -> Result<u64> {\n    let conn = open(db_path)?;\n    ann_index_signature_on(&conn)\n}\n\npub(crate) fn ann_index_signature_on(conn: &Connection) -> Result<u64> {\n    let mut stmt = conn.prepare(\n        "SELECT rowid, path, size, modified, COALESCE(embedding_dim, 0), embedding_normalized, embedding FROM images WHERE embedding IS NOT NULL ORDER BY rowid",\n    )?;\n    let rows = stmt.query_map([], |row| {\n        Ok((\n            row.get::<_, i64>(0)?,\n            row.get::<_, String>(1)?,\n            row.get::<_, i64>(2)?,\n            row.get::<_, i64>(3)?,\n            row.get::<_, i64>(4)?,\n            row.get::<_, bool>(5)?,\n            row.get::<_, Vec<u8>>(6)?,\n        ))\n    })?;\n    let mut hasher = std::collections::hash_map::DefaultHasher::new();\n    2_u32.hash(&mut hasher); // v2 includes the durable vector bytes themselves.\n    for row in rows {\n        let (rowid, path, size, modified, dim, normalized, embedding) = row?;\n        rowid.hash(&mut hasher);\n        path.hash(&mut hasher);\n        size.hash(&mut hasher);\n        modified.hash(&mut hasher);\n        dim.hash(&mut hasher);\n        normalized.hash(&mut hasher);\n        embedding.hash(&mut hasher);\n    }\n    Ok(hasher.finish())\n}\n'''
if new not in text:
    if text.count(old) != 1:
        raise SystemExit(f"signature anchor count={text.count(old)}")
    text = text.replace(old, new, 1)

anchor = '''    #[test]\n    fn collections_persist_deduplicate_recursive_membership_and_delete_safely() {\n'''
test = '''    #[test]\n    fn ann_signature_changes_when_same_dimension_embedding_content_changes() {\n        let db_path = temp_db_path("ann-signature-content");\n        let root = std::env::temp_dir().join("windows-image-search-ann-signature-root");\n        let image = root.join("a.jpg");\n        {\n            let conn = open(&db_path).unwrap();\n            upsert_image(\n                &conn,\n                &image,\n                &root,\n                "a.jpg",\n                "jpg",\n                100,\n                200,\n                32,\n                32,\n                "",\n                "",\n                [1, 2, 3],\n                7,\n                &[1.0, 0.0],\n            )\n            .unwrap();\n            set_embedding(&conn, &image, &[1.0, 0.0]).unwrap();\n        }\n        let first = ann_index_signature(&db_path).unwrap();\n        let unchanged = ann_index_signature(&db_path).unwrap();\n        assert_eq!(first, unchanged);\n        {\n            let conn = open(&db_path).unwrap();\n            set_embedding(&conn, &image, &[0.0, 1.0]).unwrap();\n        }\n        let second = ann_index_signature(&db_path).unwrap();\n        assert_ne!(first, second);\n        let _ = std::fs::remove_file(&db_path);\n        let _ = std::fs::remove_file(format!("{}-wal", db_path.display()));\n        let _ = std::fs::remove_file(format!("{}-shm", db_path.display()));\n    }\n\n'''
if test not in text:
    if text.count(anchor) != 1:
        raise SystemExit(f"test anchor count={text.count(anchor)}")
    text = text.replace(anchor, test + anchor, 1)

path.write_text(text, encoding="utf-8")
print("ANN signature content fix applied")
