from pathlib import Path


def once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise SystemExit(f"missing patch target: {label}")
    return text.replace(old, new, 1)


path = Path("src/ui/mod.rs")
text = path.read_text(encoding="utf-8")
old = """                    ui.separator();\n\n                    let fit_label = match self.thumb_fit {\n                        ThumbnailFit::Contain => \"Fit: Contain\",\n                        ThumbnailFit::Cover => \"Fit: Cover\",\n                    };\n                    if ui.button(fit_label).clicked() {\n                        self.thumb_fit = match self.thumb_fit {\n                            ThumbnailFit::Contain => ThumbnailFit::Cover,\n                            ThumbnailFit::Cover => ThumbnailFit::Contain,\n                        };\n                    }\n\n                    ui.add(\n                        egui::Slider::new(&mut self.thumb_size, 96.0..=512.0)\n                            .text(\"Size\")\n                            .suffix(\" px\"),\n                    );\n"""
new = """                    ui.separator();\n                    ui.menu_button(\"Display\", |ui| {\n                        ui.strong(\"Thumbnail fit\");\n                        ui.selectable_value(\n                            &mut self.thumb_fit,\n                            ThumbnailFit::Contain,\n                            \"Contain whole image\",\n                        );\n                        ui.selectable_value(\n                            &mut self.thumb_fit,\n                            ThumbnailFit::Cover,\n                            \"Cover tile\",\n                        );\n                        ui.separator();\n                        ui.checkbox(&mut self.inspector_open, \"Show Inspector\");\n                    });\n\n                    ui.add_sized(\n                        [150.0, 20.0],\n                        egui::Slider::new(&mut self.thumb_size, 96.0..=512.0)\n                            .text(\"Size\")\n                            .suffix(\" px\")\n                            .integer(),\n                    );\n"""
text = once(text, old, new, "display menu")
path.write_text(text, encoding="utf-8")


path = Path("src/ui/views.rs")
text = path.read_text(encoding="utf-8")
text = once(text, "use super::{ImageSearchApp, ThumbnailFit};\n", "use super::{ImageSearchApp, SortMode, ThumbnailFit};\n", "views SortMode import")
text = once(
    text,
    """        let widths = DetailWidths::from_total(available);\n        detail_header(ui, widths);\n        ui.separator();\n""",
    """        let widths = DetailWidths::from_total(available);\n        if let Some(sort_mode) = detail_header(ui, widths, self.sort_mode) {\n            self.sort_mode = sort_mode;\n        }\n        ui.separator();\n""",
    "details header sort hook",
)
old = """fn detail_header(ui: &mut egui::Ui, widths: DetailWidths) {\n    ui.horizontal(|ui| {\n        ui.spacing_mut().item_spacing.x = 0.0;\n        ui.add_sized([widths.thumb, 22.0], egui::Label::new(\"\"));\n        ui.add_sized(\n            [widths.name, 22.0],\n            egui::Label::new(egui::RichText::new(\"Name\").strong()),\n        );\n        ui.add_sized(\n            [widths.info, 22.0],\n            egui::Label::new(egui::RichText::new(\"Info\").strong()),\n        );\n        ui.add_sized(\n            [widths.color, 22.0],\n            egui::Label::new(egui::RichText::new(\"Color\").strong()),\n        );\n        ui.add_sized(\n            [widths.metadata, 22.0],\n            egui::Label::new(egui::RichText::new(\"Metadata\").strong()),\n        );\n        ui.add_sized(\n            [widths.score, 22.0],\n            egui::Label::new(egui::RichText::new(\"Score\").strong()),\n        );\n    });\n}\n"""
new = """fn detail_header(\n    ui: &mut egui::Ui,\n    widths: DetailWidths,\n    current_sort: SortMode,\n) -> Option<SortMode> {\n    let mut requested_sort = None;\n    ui.horizontal(|ui| {\n        ui.spacing_mut().item_spacing.x = 0.0;\n        ui.add_sized([widths.thumb, 22.0], egui::Label::new(\"\"));\n\n        let name_label = if current_sort == SortMode::Name {\n            \"Name ▲\"\n        } else {\n            \"Name\"\n        };\n        if ui\n            .add_sized([widths.name, 22.0], egui::Button::new(name_label).frame(false))\n            .on_hover_text(\"Sort by filename\")\n            .clicked()\n        {\n            requested_sort = Some(SortMode::Name);\n        }\n\n        ui.allocate_ui_with_layout(\n            egui::vec2(widths.info, 22.0),\n            egui::Layout::left_to_right(egui::Align::Center),\n            |ui| {\n                ui.set_min_width(widths.info);\n                ui.set_max_width(widths.info);\n                ui.menu_button(\"Info sort ▾\", |ui| {\n                    if ui\n                        .selectable_label(current_sort == SortMode::Resolution, \"Resolution\")\n                        .clicked()\n                    {\n                        requested_sort = Some(SortMode::Resolution);\n                        ui.close();\n                    }\n                    if ui\n                        .selectable_label(current_sort == SortMode::Modified, \"Modified date\")\n                        .clicked()\n                    {\n                        requested_sort = Some(SortMode::Modified);\n                        ui.close();\n                    }\n                    if ui\n                        .selectable_label(current_sort == SortMode::Size, \"File size\")\n                        .clicked()\n                    {\n                        requested_sort = Some(SortMode::Size);\n                        ui.close();\n                    }\n                });\n            },\n        );\n\n        ui.add_sized(\n            [widths.color, 22.0],\n            egui::Label::new(egui::RichText::new(\"Color\").strong()),\n        );\n        ui.add_sized(\n            [widths.metadata, 22.0],\n            egui::Label::new(egui::RichText::new(\"Metadata\").strong()),\n        );\n\n        let score_label = if current_sort == SortMode::Relevance {\n            \"Score ▼\"\n        } else {\n            \"Score\"\n        };\n        if ui\n            .add_sized([widths.score, 22.0], egui::Button::new(score_label).frame(false))\n            .on_hover_text(\"Restore relevance / similarity order\")\n            .clicked()\n        {\n            requested_sort = Some(SortMode::Relevance);\n        }\n    });\n    requested_sort\n}\n"""
text = once(text, old, new, "sortable details header")
path.write_text(text, encoding="utf-8")
